# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DoAn_CNPM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
pod 'Alamofire'
pod 'KRProgressHUD'
pod 'SwiftyJSON'
  use_frameworks!

  # Pods for DoAn_CNPM

  target 'DoAn_CNPMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoAn_CNPMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
